version: '3.8'

services:
  app:
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    volumes:
      - .:/var/www/html
      - ./uploads:/var/www/html/uploads
      - ./logs:/var/log/apache2

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=inventory_system
      - MYSQL_USER=inventory_user
      - MYSQL_PASSWORD=inventory_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  mysql_data:
